Jobs/urls.py
from django.urls import path
from .views import *

app_name = 'jobs'

urlpatterns = [
    path('',jobCreateView.as_view(), name = 'job_create'),

   
]

accounts/urls.py
from django.urls import path
from .views import *

app_name = 'accounts'


urlpatterns = [
   

    path('', loginView.as_view(), name='login'),

    path('signup/', signupView.as_view(), name='signup'),

    path('logout/', logoutView.as_view(), name='logout'),

    path('forgot/', forgotView.as_view(), name='forgot_password'),

    path('profile/', RegisterView.as_view(), name='profile'),

    path('address/', addressView.as_view(), name = 'address'),

    path('detailes/', userDetailesView.as_view(), name = 'userdetailes'),

    path('detailes/user-selection', userSelectionView.as_view(), name = 'userselection'),

    path('detailes/user-selection/jobseeker', jobSeekerView.as_view(), name = 'jobseeker'),


    path('detailes/user-selection/employer', employerView.as_view(), name = 'employer'),

    path('employer/', employerLandingView.as_view(), name = 'employerlanding'),


    path('home/', userLandingView.as_view(), name = 'userlanding'),

    path('home/jobseeker', jsHomeView.as_view(), name = 'jshome'),

    path('home/post-job', jobPostView.as_view(), name = 'jobpost'),

    path('home/posted-jobdetailes', EmployerPostedJobView.as_view(), name = 'postedjobdetailes')


    
    
  
]

jobportal/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', include("jobportal_app.urls")),
    path('admin-page/', include("administration.urls")),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('jobs/', include('Jobs.urls', namespace='jobs')),
   
    
    

]

templates/partials/footer.html
<div class="container">
    <div class="footer-wrapper">
        <div class="row">
            <div class="col-md-6 col-lg-6">
                <div class="footer-logo-content">
                    <div class="footer-logo">
                        <a class="navbar-brand py-0 me-0" href="#"><h3 class="dark">Comapny Detailes</h3></a>
                    </div>
                    <div class="footer-item-content">
                        <p class="text fs-7">
                           Start your career journey with us,
                           where we connect your talents with
                           endless opportunities for growth and 
                           success
                        </p>
                    </div>
                    <div class="socials-icon">
                        <ul class="d-flex align-items-center list-unstyled mb-0">
                            <li>
                                <a class="d-flex align-items-center justify-content-center rounded-circle text-decoration-none facebook-icon" href="#">
                                    <i class="ti ti-brand-facebook"></i>
                                </a>
                            </li>
                            <li>
                                <a class="d-flex align-items-center justify-content-center rounded-circle text-decoration-none twitter-icon" href="#">
                                    <i class="ti ti-brand-twitter"></i>
                                </a>
                            </li>
                            <li>
                                <a class="d-flex align-items-center justify-content-center rounded-circle text-decoration-none instagram-icon" href="#">
                                    <i class="ti ti-brand-instagram"></i>
                                </a>
                            </li>
                            <li>
                                <a class="d-flex align-items-center justify-content-center rounded-circle text-decoration-none youtube-icon" href="#">
                                    <i class="ti ti-brand-youtube"></i>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-lg-2">
                <div class="footer-link-list">
                    <h5 class="footer-title fw-normal">Support</h5>
                    <ul class="list-unstyled mb-0">
                      
                        <li><a class="text-decoration-none fs-7" href="#">Contact Us</a></li>
                        <li><a class="text-decoration-none fs-7" href="#">Terms & Condition</a></li>
                        <li><a class="text-decoration-none fs-7" href="#">Privacy</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md-6 col-lg-4">
                <div class="footer-contact-us">
                    <h5 class="footer-title fw-normal">Contact Us</h5>
                    <div class="call">
                        <a class="text-decoration-none d-flex align-items-center" href="tel:(406)555-0120">
                            <!-- <img src="call.svg" alt=""> -->
                            +91 9674589345
                        </a>
                    </div>
                    <div class="mailto">
                        <a class="text-decoration-none d-flex align-items-center" href="mailto:tim.jennings@example.com">
                            <!-- <img src="mail.svg" alt=""> -->
                            job.jobportals@example.com
                        </a>
                    </div>
                    <div class="address">
                        <p class="text mb-0 fs-7 d-flex align-items-center">
                            <!-- <img src="home.svg" alt=""> -->
                            ABC building, kochi 612 499
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="copyright-text text-center">
    <p class="text mb-0">@2024 - All Rights Reserved by <a href="https://adminmart.com/" class="primary-text text-decoration-none">JobPoratl.com</a></p>
</div>

templates/partials/navbar.html
{% load static %}
<div class="container">
    <nav class="navbar navbar-expand-lg py-0">
        <div class="container-fluid">
            <div class="logo d-flex align-items-center justify-content-between">
                <a class="navbar-brand py-0 me-0" href="#"><h2>JobPortal</h2></a>
                <!-- mobile toggle -->
                <a class="navbar-toggler d-block d-lg-none border-0 p-0" data-bs-toggle="offcanvas"
                    href="#offcanvasExample" role="button" aria-controls="offcanvasExample">
                    
                </a>
            </div>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mx-auto mb-2 mb-lg-0">

                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="#">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Jobs</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Company</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">contact</a>
                    </li>
                    <li class="nav-item">
            {% if user.is_authenticated %}
                       <form class="d-flex my-2 my-lg-0 mr-0 pr-100">
                          <input class="form-control me-sm-2" type="text" placeholder="Search" />
                          <a class="nav-link" href="#">
                            <button class="btn btn-primary get-stared btn-sm"  type="submit">
                                Search
                               </button> 
                          </a>  
                       </form>
               
                       
                    </li>
                   
                    <li class="nav-item">
                         <a class="nav-link dropdown" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                          <img src="{% static 'img/JobPortal_notification.png' %}" alt="notification">
                    {% comment %} <span class="badge badge-danger" id="notification-count">3</span> <!-- Notification count --> {% endcomment %}
                         </a>
                         <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="#">Message 1</a>
                            <a class="dropdown-item" href="#">Message 2</a>
                            <a class="dropdown-item" href="#">Message 3</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#">See all notifications</a>
                            </div>
                    </li>
                    <li class="nav-item">
                         <a class="nav-link dropdown" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                          <img src="{% static 'img/JobPortal_profile.png' %}" alt="notification">
                    {% comment %} <span class="badge badge-danger" id="notification-count">3</span> <!-- Notification count --> {% endcomment %}
                         </a>
                         <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">

                            <a class="dropdown-item" href="#">Profile</a>
                              <a class="dropdown-item" href="#">Edit</a>
                              <a class="dropdown-item" href="#">add address</a>                  
                            <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="{% url 'accounts:logout' %}">logout</a>
                            </div>
                        </div>
                    </li>
                    </li>
                </ul>
               
                
                
                
             {% else %}    
                <div class="login d-lg-flex align-items-center">
                    <a class="btn btn-primary bg-transparent sign-in" href="#"></a>
                    <a class="btn btn-primary get-stared" href="{% url 'accounts:signup' %}">Signup </a>
                </div>
            {% endif %}
                
            </div>
        </div>
    </nav>
</div>