Jobs/urls.py
from django.urls import path
from .views import *

app_name = 'jobs'

urlpatterns = [
    path('',jobCreateView.as_view(), name = 'job_create'),

   
]

accounts/urls.py
from django.urls import path
from .views import *

app_name = 'accounts'


urlpatterns = [
   

    path('', loginView.as_view(), name='login'),

    path('signup/', signupView.as_view(), name='signup'),

    path('logout/', logoutView.as_view(), name='logout'),

    path('forgot/', forgotView.as_view(), name='forgot_password'),

    path('profile/', RegisterView.as_view(), name='profile'),

    path('address/', addressView.as_view(), name = 'address'),

    path('detailes/', userDetailesView.as_view(), name = 'userdetailes'),

    path('detailes/user-selection', userSelectionView.as_view(), name = 'userselection'),

    path('detailes/user-selection/jobseeker', jobSeekerView.as_view(), name = 'jobseeker'),


    path('detailes/user-selection/employer', employerView.as_view(), name = 'employer'),

    path('employer/', employerLandingView.as_view(), name = 'employerlanding'),


    path('home/', userLandingView.as_view(), name = 'userlanding'),

    path('home/jobseeker', jsHomeView.as_view(), name = 'jshome'),

    path('home/post-job', jobPostView.as_view(), name = 'jobpost'),

    path('home/posted-jobdetailes', EmployerPostedJobView.as_view(), name = 'postedjobdetailes')


    
    
  
]

jobportal/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', include("jobportal_app.urls")),
    path('admin-page/', include("administration.urls")),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('jobs/', include('Jobs.urls', namespace='jobs')),
   
    
    

]

accounts/forms.py
from django.forms import ModelForm, Form, DateInput, SelectMultiple
from django.forms import TextInput, PasswordInput, CharField, EmailInput,Textarea,Select,CheckboxInput, FileInput
from django.core.validators import MinLengthValidator
from .models import *


class LoginForm(Form):
    username = CharField(
        max_length= 15,
        min_length= 4,
        required= True,
        label= 'Username',
        widget= TextInput({
            'class': 'form-control',
            'placeholder':'User Name'

        })

    )
    password = CharField(
        max_length= 15,
        min_length= 4,
        required= True,
        label= 'Password',
        widget= PasswordInput({
            'class': 'form-control',
            'placeholder':'Password'
        })

    )

class ForgotForm(ModelForm):
        
        username = CharField(
        max_length= 15,
        min_length= 4,
        required= True,
        label= 'Username',
        widget= TextInput({
            'class': 'form-control',
            'placeholder':'User Name'

        })

       )
        class Meta:
            model = User
            fields = [
                
                'email'
            ]
            widgets =  {
                        
                

                    'email' : EmailInput({
                        'class':'form-control',
                        'placeholder':'email'

                        
                    })

                
            }



class UserRegisterForm(ModelForm):

    confirm_password = CharField(
        max_length = 25,
        min_length = 8,
        required = True,
        validators = [
            MinLengthValidator(8, 'The password is too short.')
        ],
        widget = PasswordInput({
            'class': 'form-control',
            'placeholder':'Confirm Password'
        })
    )


    



    class Meta:
        model = User
        fields = [
           
            'first_name',
            'last_name',
            'username',
            'email',
            'password',
            'phone',
            'dob',
            'short_bio',
            'job_title',
            'gender',
            'country',
            'open_to_hiring',
            'profile_photo',
            'age'


        ]
        widgets = {
            'username': TextInput({
                'class': 'form-control',
                'placeholder':'Username'
            }),

            'first_name': TextInput({
                'class': 'form-control'
            }),

            'last_name': TextInput({
                'class': 'form-control'
            }),

            'password': PasswordInput({
                'class': 'form-control',
                'placeholder':'Password'
            }),

            'email': EmailInput({
                'class': 'form-control',
                'placeholder':'email'
            }),

            'phone': TextInput({
                'class': 'form-control',
                'placeholder':'phone'
                 
            }),

            'dob': DateInput({
                'class': 'form-control',
                'placeholder':'YYYY-MM-DD'
            }),

            'short_bio': Textarea({
                'class': 'form-control',
                'rows': '3',
                'placeholder':'Short-Bio'
            }),

            'job_title': TextInput({
                'class': 'form-control'
            }),

            'gender': Select({
                'class': 'form-control'
            }),

            'country': Select({
                'class': 'form-control'
            }),
            'age' : TextInput({
                'class': 'form-control',
                'placeholder':'Enter Age'
            })
           


        }




class JobSeekerForm(ModelForm):
      class Meta:
        model = JobSeeker
        fields = [
            'title',
            'expertise_level'
         ]
        widgets =  {
                     
            
                'title' : TextInput({
                    'class':'form-control',
                     'placeholder':'Title'
                    
                }),

                'expertise_level' : Select({
                    'class':'form-control',
                    
                })

            
        }



class EmployerForm(ModelForm):
      class Meta:
        model = Employer
        fields = [
            'company_name',
            'designation',
            'location'
         ]
        widgets =  {
                     
            
                'company_name' : TextInput({
                    'class':'form-control',
                     'placeholder':'Company Name'
                    
                }),

                'designation' : Select({
                    'class':'form-control',
                    'placeholder':'Select Designation'

                    
                 }),
                'location' : Select({
                    'class':'form-control',
                    'placeholder':'Select Location'

                    
                })

            
        }

class UserDetailesForm(ModelForm):


    class Meta:
        model = User
        fields = [
           
            'hobbies',
            'interest',
            'qualification',
            'multiple_images',
            'short_reel',
            'smoking_habit',
            'drinking_habit',
            'profile_photo',
            'age',
            'dob'


        ]
        widgets = {
            
            'dob': DateInput({
                'class': 'form-control',
                'placeholder':'YYYY-MM-DD'
            }),

            'hobbies': SelectMultiple({
                'class': 'form-control'
            }),
            'qualification': SelectMultiple({
                'class': 'form-control'
            }),
            'interest': SelectMultiple({
                'class': 'form-control'
            }),
            'age' : TextInput({
                'class': 'form-control',
                'placeholder':'Enter Age'
            }),
            'multiple_images' : FileInput({
                'class': 'form-control',
                
            }),
            'short_reel' : FileInput({
                'class': 'form-control',
                
            })

 

        }


















#user detailes  

# class UserDetailesForm(ModelForm):
#     class Meta:
#         model = UserActivity

#         exclude = ['user']
#         fields = [
           
#             'hobbies',
#             'interest',
#             'smoking_habit',
#             'drinking_habit',
#             'user_images',
#             'user_reels',
#             'user_qualification'

#         ]

#         widgets = {
#             'hobbies': Select({
#                 'class': 'form-control',
#                 'placeholder':'Choose'
#             }),
#             'interest': Select({
#                 'class': 'form-control',
#                 'placeholder':'Choose'
#             }),
#             'smoking_habit': Select({
#                 'class': 'form-control'
                
#             }),
#             'drinking_habit': Select({
#                 'class': 'form-control'
                
#             }),
#             'user_qualification': TextInput({
#                 'class': 'form-control',
#                 'placeholder':'Choose'
#             }),

#         }

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.shortcuts import render, HttpResponse
from django.contrib.auth import authenticate, login,logout
from .forms import *
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse, reverse_lazy

# Create your views here.
from django.views import View
from django.views.generic import CreateView,  View


class loginView(View):
    form_class = LoginForm
    template_name = 'accounts/login.html'
    template_user = 'accounts/userdetailes.html'
    form_class1 = UserRegisterForm
    
    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, {'form':self.form_class()})
   
    def post(self, request, *args, **kwargs):
        form = self.form_class(data = request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect("accounts:userdetailes")
            else:
                return HttpResponse('Invalid username or password')
        #form is not valid then..
        return render(request, self.template_name, {'form': form} )

  
 

class signupView(View):
    form_class = UserRegisterForm
    template_name = 'accounts/signup.html'
    template_login = 'accounts/login.html'

    def get(self, request, *args, **kwargs):
         return render(request, self.template_name, {'form': self.form_class()})
    
    def post(self, request, *args, **kwargs):
        form = self.form_class(data = request.POST)
        if not form.is_valid():
            return render(request, self.template_name, {'form': form})
        #form is valid then..
        user = form.save(commit=False)
        user.set_password(user.password)
        user.save()
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user = authenticate(request, username=username, password=password)

        login(request, user)
        return redirect(reverse('accounts:userdetailes'))

   
class logoutView(LoginRequiredMixin, View):
    def get(self, request):
        logout(request)
        return redirect(reverse('accounts:login'))
   

        
    


class forgotView(View):
    form_class = ForgotForm 
    template_name = 'accounts/forgot_password.html'

    def get(self, request):

        return render(request, self.template_name, {'form':self.form_class})

    
   




#for profile
class RegisterView(View):
       
    form_class = UserRegisterForm
    template_name = 'accounts/register.html'

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, {'form':  self.form_class()})
    
    def post(self, request, *args, **kwargs):
        form = self.form_class(data = request.POST)

        if not form.is_valid():
            return render(request, self.template_name, {'form': form})
        
        #form is valid then
        user = form.save(commit=False)
        user.password = form.cleaned_data['password']
        user.save()
        return HttpResponse("successfully entered profile detail")



#for address creation

class addressView(View):
    template_name = 'accounts/address_create.html'

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)
    


#for userdetailes(2nd page)

class userDetailesView(LoginRequiredMixin, View):
    form_class = UserDetailesForm
    template_name = 'accounts/userdetailes.html'
    

    def get(self, request):
        return render(request, self.template_name, {'form': self.form_class()})
    
    def post(self, request):
        form = self.form_class(request.POST)
        if not form.is_valid():
            return render(request, self.template_name, {'form': form})
        
        user = self.request.user
        
        hobbies = form.cleaned_data['hobbies']
        interest = form.cleaned_data['interest']
        user.drinking_habit = form.cleaned_data['drinking_habit']
        qualification = form.cleaned_data['qualification']
        multiple_images = form.cleaned_data['multiple_images']
        short_reel = form.cleaned_data['short_reel']
        user.smoking_habit = form.cleaned_data['smoking_habit']
        user.age = form.cleaned_data['age']
        if 'profile_photo' in form.cleaned_data:
            user.profile_photo = form.cleaned_data['profile_photo']
            user.save()
            #for saving many to many field
        user.hobbies.set(hobbies)
        user.interest.set(interest)
        user.qualification.set(qualification)
        user.multiple_images.set(multiple_images)
        user.short_reel.set(short_reel)
        
        return redirect(reverse('accounts:userselection'))




    # def get(self, request):
    #      return render(request, self.template_name, {'form': self.form_class()})
    
    # def post(self, request):
    #     form = self.form_class(data = request.POST)
    #     if not form.is_valid():
    #         return render(request, self.template_name, {'form': form})
    #     #form is valid then..
    #     user_details = form.save(commit=False)
    #     user_details.user = request.user  
    #     user_details.save()
        
    #     return redirect('accounts:userselection')
    
    
 

class userSelectionView(LoginRequiredMixin, View):
     template_name = 'accounts/user_selection.html'

     def get(self, request, *args, **kwargs):
        return render(request, self.template_name )


#for jobseeker page
class jobSeekerView(LoginRequiredMixin, View):

    form_class = JobSeekerForm
    template_name = 'accounts/jobseeker.html'
    

    def get(self, request):
        return render(request, self.template_name, {'form': self.form_class()})
    
    def post(self, request):
        form = self.form_class(request.POST)
        if not form.is_valid():
            return render(request, self.template_name, {'form': form})
        
        form.instance.user = self.request.user
        form.save()

        return redirect(reverse('accounts:userlanding'))







class employerView(LoginRequiredMixin, View):

    form_class = EmployerForm
    template_name = 'accounts/employer.html'
    

    def get(self, request):
        return render(request, self.template_name, {'form': self.form_class()})
    
    def post(self, request):
        form = self.form_class(request.POST)
        if not form.is_valid():
            return render(request, self.template_name, {'form': form})
        
        form.instance.user = self.request.user
        form.save()
        
        
        return redirect(reverse('accounts:employerlanding'))



class userLandingView(View):
    template_name = 'accounts/userlandingpage.html'

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)


class jobPostView(View):
   
    template_name = 'accounts/postjob.html'

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)

 #employer to get detailes of posted jobs   

class EmployerPostedJobView(View):
   
    template_name = 'accounts/em_posted_jobdetailes.html'

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)
    
#employer landing page
class employerLandingView(View):
   
    template_name = 'accounts/em_landing.html'

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)
    
#displaying home page for jobseeker
class jsHomeView(View):
   
    template_name = 'accounts/js_home.html'

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)

templates/accounts/address_create.html
{% extends 'base.html' %}


{% block content %}
    <div class="container fluid">
        <div class="row">
            <div class="col-sm-4 offset-sm-4">
                <h1 class="text-center mt-5">Create Address</h1>
                <form method="post">
                    {{ form.as_p }}
                    <div class="d-grid">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-primary mt-2">Login</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

templates/accounts/address_upsert.html
{% extends 'base.html' %}


{% block accounts_content %}
    <div class="container-fluid">
        <h1 class="text-center">Address</h1>
        <form method="post">
            {{ form.as_p }}
            <div class="d-grid">
                {% csrf_token %}
                <button type="submit" class="btn btn-primary mt-2">Save</button>
            </div>
        </form>
    </div>
{% endblock accounts_content %}

templates/accounts/employer.html
{% extends "base.html" %}


{% block content %}
<div class="container bootstrap snippet">
    
    <div class="row">
          
        {% comment %} <div class="col-sm-2"><a href="/users" class="pull-right"><img title="profile image" class="img-circle img-responsive" src="http://www.gravatar.com/avatar/28fd20ccec6865e2d5f0e1f4446eb7bf?s=100"></a></div> {% endcomment %}
    </div>
    <div class="row">
          <div class="col-sm-3"><!--left col-->
              

      <div class="text-center">
        <h4 class="text-center">Welcome...<h4>
        <img src="http://ssl.gstatic.com/accounts/ui/avatar_2x.png" class="avatar img-circle img-thumbnail" alt="avatar">
        <div class="col-sm-10"><h1 class="hed">User name</h1></div>
       
    </div></hr><br>

     
          
        </div><!--/col-3-->
        <div class="col-sm-9">
            <ul class="nav nav-tabs">
                <ul class="nav nav-tabs">
                    <li class="nav-item">
                        <a class="nav-link active" data-toggle="tab" href="#home" style="background-color: #f0f0f0; color: #333;">Personal</a>
                    </li>
                    
                </ul>
              </ul>

              
           <div class="tab-content">
            <div class="tab-pane active" id="home">
                <hr>  
                  <form  method="post" >
                    {% csrf_token %}
                      <div class="form-group">
                        <label class="labels">Company Name</label>
                        {% include 'components/form_field.html' with field=form.company_name %}
                      </div>
                      <div class="form-group">
                        <label class="labels">Designation</label>
                         {% include 'components/form_field.html' with field=form.designation %}
                      </div> 
                      <div class="form-group">
                        <label class="labels">Location</label> 
                        {% include 'components/form_field.html' with field=form.location %}
                     </div>
          
                      
                      
                           <div class="col-xs-12">
                                <br>
                                 
                                  <button class="btn btn-lg btn-success" type="submit">Save</button>
                                   {% comment %} <button class="btn btn-lg" type="reset"><i class="glyphicon glyphicon-repeat"></i> Reset</button> {% endcomment %}
                            </div>
                        
                      </div>
                 
              
              <hr>
              
             </div><!--/tab-pane--> 
             
                    
                   
                 
               
              </div><!--/tab-pane-->
          </div><!--/tab-content-->

        </div><!--/col-9-->
    </div><!--/row-->
    
{% endblock content %}
    

templates/accounts/forgot_password.html
{% extends "base.html" %}


{% block content %}


<div class="container mt-5 pt-0">
    <div class="row justify-content-center">
        <div class="col-12 col-sm-10 col-md-8 col-lg-6 col-xl-4">
          
            <div class="container-centered">
                <div class="container-centered">
                    <h1 class="hed">Forgot Password</h1>
                    </div>
                <form>
                    <div class="form-row">
                        <div class="form-group col-12">
                            <label for="">{{ form.username.label }}</label>
                          {{ form.username }}
                        </div>
                       
                    </div>
                   
                   
                    <div class="form-group">
                        <label for="">{{ form.email.label }}</label>
                        {{ form.email }}
                       
                    </div>
                   
                    <button  class="btn btn-primary w-100">Submit </button>
                    <p class="form-text mt-3"><a href="{% url 'accounts:login' %}">Signin</a></p>
                </form>
            </div>
        </div>
    </div>
</div>

    
{% endblock content %}
    
        
      

       

  

templates/accounts/jobseeker.html
{% extends "base.html" %}


{% block content %}



<div class="container bootstrap snippet">
    
    <div class="row">
          
        {% comment %} <div class="col-sm-2"><a href="/users" class="pull-right"><img title="profile image" class="img-circle img-responsive" src="http://www.gravatar.com/avatar/28fd20ccec6865e2d5f0e1f4446eb7bf?s=100"></a></div> {% endcomment %}
    </div>
    <div class="row">
          <div class="col-sm-3"><!--left col-->
              

      <div class="text-center">
        <h4 class="text-center">Welcome...<h4>
        <img src="http://ssl.gstatic.com/accounts/ui/avatar_2x.png" class="avatar img-circle img-thumbnail" alt="avatar">
        <div class="col-sm-10"><h1 class="hed">User name</h1></div>
       
    </div></hr><br>

     
          
        </div><!--/col-3-->
        <div class="col-sm-9">
            <ul class="nav nav-tabs">
                <ul class="nav nav-tabs">
                    <li class="nav-item">
                        <a class="nav-link active" data-toggle="tab" href="#home" style="background-color: #f0f0f0; color: #333;">Personal</a>
                    </li>
                    
                </ul>
              </ul>

              
           <div class="tab-content">
            <div class="tab-pane active" id="home">
                <hr>  
                  <form   method="post">
                       {% csrf_token %}
                      <div class="form-group">
                        {% include 'components/form_field.html' with field=form.title %}
                      </div>
                      <div class="form-group">
                          
                         {% include 'components/form_field.html' with field=form.expertise_level %}
                      </div>
          
                      
                      
                           <div class="col-xs-12">
                                <br>
                                  {{ form.errors }}
                                  <button class="btn btn-lg btn-success" type="submit"> Save</button>
                                   {% comment %} <button class="btn btn-lg" type="reset"><i class="glyphicon glyphicon-repeat"></i> Reset</button> {% endcomment %}
                            </div>
                        </form>
                      </div>
                 
              
              <hr>
              
             </div><!--/tab-pane--> 
             
                    
                   
                 
               
              </div><!--/tab-pane-->
          </div><!--/tab-content-->

        </div><!--/col-9-->
    </div><!--/row-->
    
{% endblock content %}
    

templates/accounts/login.html
{% extends "base.html" %}


{% block content %}

<div class="container mt-5 pt-0">
    <div class="row justify-content-center">
        <div class="col-12 col-sm-10 col-md-8 col-lg-6 col-xl-4">
            <div class="container-centered">
                <div class="container-centered">
                    <h1 class="hed"> Login</h1>
                    </div>
                 <form method="post">
                          {% csrf_token %}
                        <div class="form-row">
                            <div class="form-group col-12">
                              <label for="">{{ form.username.label }}</label>
                              {{ form.username }}
                    
                              {{ form.username.errors.as_ul }}
                            </div>
                        </div>
                
                <div class="form-group">
                    <label for="">{{ form.password.label }}</label>
                    {{ form.password }}

                    {% if form.password.errors %}
                        <div class="alert alert-danger">
                            {% for e in form.password.errors %}
                                <p class="text-danger">{{ e }}</p>
                            {% endfor %}
                        </div>
                    {% endif %}

                 </div>
                 <div class="form-group">
                   
                    <button type="submit" class="btn btn-primary w-100">Login</button>
                    <p class="form-text mt-3">Already have an account? <a href="{% url 'accounts:forgot_password' %}">Forgot Password</a></p>
                 </div>
             </form>
          </div>

        </div>
    </div>
</div>

    
{% endblock content %}
    
    
    

templates/accounts/signup.html
{% extends "base.html" %}


{% block content %}


<div class="container mt-5 pt-0">
    <div class="row justify-content-center">
        <div class="col-12 col-sm-10 col-md-8 col-lg-6 col-xl-4">
            <div class="container-centered">
                <div class="container-centered">
                    <h1 class="hed">Signup</h1>
                    </div>
                <form method="post">
                    {% csrf_token %}
                    <div class="form-row">
                        <div class="form-group col-12">
                            <label for="" >{{ form.username.label }}</label>
                            {{ form.username }}
                        </div>
                       
                    </div>
                    <div class="form-group">
                        <label for="">{{ form.email.label }}</label>
                        {{ form.email }}
                    </div>
                   
                    <div class="form-group">
                        <label for="">{{ form.password.label }}</label>
                        {{ form.password }}
                    </div>
                    <div class="form-group">
                        <label for="">{{ form.confirm_password.label }}</label>
                        {{ form.confirm_password }}
                    </div>
                     {{ form.errors }}
                    <button type="submit" class="btn btn-primary w-100">Signup</button>
                    <p class="form-text mt-3">Already have an account? <a href="{% url 'accounts:forgot_password' %}">Forgot Password</a></p>
                </form>
            </div>
        </div>
    </div>
</div>
    
{% endblock content %}
    

       
        
       

      

templates/accounts/user_selection.html
{% extends "base.html" %}
    {% load static %}

    
    {% block content %}
    <link rel="stylesheet" href="{% static 'css/glowbt.css' %}" />
    <title>Glowing Text Button | Coding Vibess</title>
   

  
    

<h1 class="hed">Choose</h1>
<div class="container mt-5 pt-0">
  <div class="row justify-content-center">
      <div class="col-12 col-sm-10 col-md-8 col-lg-6 col-xl-4">
          <div class="container-centered">
             
          
            <div class="container mt-4 h-100 d-flex justify-content-center align-items-center">
              <a class="text-decoration-none"  href="{% url 'accounts:jobseeker' %}">
              <button  class='glowbt'>
              <span> JobSeeker</span>
             </button>
            </a>
           </div>
                
               

      </div>
  </div>
</div>

<div class="container mt-5 pt-0">
  <div class="row justify-content-center">
      <div class="col-12 col-sm-10 col-md-8 col-lg-6 col-xl-4">
          <div class="container-centered">
             
          
            
           <div class="container mt-4 h-100 d-flex justify-content-center align-items-center">
            <a class="text-decoration-none"  href="{% url 'accounts:employer' %}">
                  <button class='glowbt'>
                      <span>Employer</span>
                 </button>
                </a>
          </div>      
               

      </div>
  </div>
</div>

<div class="container mt-5 pt-0">
  <div class="row justify-content-center">
      <div class="col-12 col-sm-10 col-md-8 col-lg-6 col-xl-4">
       
  </div>
</div>
  
    
    <script src="{% static 'js/glowbt.js' %}"></script>
 
        
    {% endblock content %}
        
    
  